### PR TITLE
Rule Amendment #1

### PR DESCRIPTION
**Pull request by JMTyler**

### CODE REVIEW

**Comment by JMTyler** [comment]
This PR needs to be rebased.  Please refrain from voting until this has been done.

**Comment by stolksdorf** [comment]
Have you rebased yet?!

**Comment by JMTyler** [comment]
Rebased.  Let voting commence.

**Comment by stolksdorf** [comment]
AGREED 2/2, price is right rules. I like it.

**Comment by robee** [comment]
3/3 - However, look for an incoming rules clarification on my turn.

**Comment by stolksdorf** [comment]
@ktrain Where you at b

**Comment by ktrain** [comment]
4/4

**Comment by stolksdorf** [comment]
@JMTyler rebase again then merge, we have full majority. Also I wanted to try adding a little [X] under the rule, where x is the pull request number and it's a link to the associated pull request then added/modified the rule.

**Pull request closed without merging**
